### PR TITLE
Add a folder for articles that explain NLP basics

### PR DESCRIPTION
**Pull request by carolina-museum**
Added a folder for articles that explain NLP basics.
One completed article and one working-on-it article are in the folder.

The plan is to keep adding preliminaries that are necessary to understand RAG and its foundation models.

- [done] NN basics 
- [working] NLP basics (NLP tasks, tokenization, traditional methods like n-grams & LSTM) 
- Transformers (architecture, improved architectures)
- RAG

### CODE REVIEW

**Comment by huyfififi** [comment]
@carolina-museum Thanks for working on this. I think your branch is not up to date with the latest main, and I'm seeing some weird diffs. Can you try

```
$ git switch main
$ git pull  # pulling the latest changes/commits
$ git switch add-nn-basics 
$ git rebase main
```

to keep your branch in sync with the latest main?

**Comment by huyfififi** [comment]
FYI: There are two ways to pull the other's changes into your local branch

```
$ git merge branch_name
$ git rebase branch_name
```

You might want to check how it works and their differences when you have some time

**Review by huyfififi — APPROVED** [review]
@carolina-museum Thanks for rebasing with the main branch 👍 now this pull request only contains one commit, and it's much easier to review.
The changes look good to me. Please merge in your good time.

**Comment by carolina-museum** [comment]
@huyfififi  Thank you for checking!
Yes, I think I didn't keep my branch up to date. 
I've done the commands you gave me.

**Pull request merged**
