### PR TITLE
add meaning of freeze Paper_P_Lewis_2021.md

### PR DESCRIPTION
**Pull request by carolina-museum**
I added more context on what freezing the learning means.🥶

### CODE REVIEW

**Comment by huyfififi** [comment]
I might be a moron, but what is the retrieval model mentioned here?
Embedding models are used to generate embeddings (vectors), but retrieving them is simply done by comparing the mathematical vector expressions, and I guess it does not involve any AI models when retrieving knowledge data?

**Review by huyfififi — APPROVED** [review]
👍

**Comment by huyfififi** [comment]
It would be great if you could add a bit more explanation about the retrieval model, as nowadays retrieval is usually done by similarity search of vectors, and people may not have a concrete understanding of the retrieval model 👍

**Comment by huyfififi** [comment]
maybe I should check the paper on how they achieve the retrieval feature with NN model 🤔

**Comment by carolina-museum** [comment]
Thank you for your review! I also want to know how they designed the learnable retrieval model :) I'll take a look and explain in the future!

**Pull request merged**
